#!/usr/bin/env python3
"""Generate RumbleRecomp controller profiles for Dolphin/ModernGekko.

Writes <user-dir>/Config/WiimoteNew.ini (sideways Wii Remote, Extension = None) and
<user-dir>/Config/Wiimote.ini (which player slots are active).

Player 1 = keyboard + first gamepad. Players 2-4 = second..fourth gamepad (no keyboard).
Devices are discovered from Dolphin's log ("Added device: ..."), so run the game once
(or pass --gamepad NAME ... explicitly). Only SDL gamepads are used (DInput/XInput
duplicates of the same pad are ignored). Keyboard keys are DirectInput names.

Rumble is played sideways:  2 = confirm / attack,  1 = secondary,  D-pad / stick = move.
"""
import argparse, os, re, sys

KEYBOARD = 'DInput/0/Keyboard Mouse'

# Wii Remote control -> (keyboard keys, SDL gamepad inputs)
MAP = {
    'Buttons/2':     (['J', 'SPACE'],                 ['Button S']),                 # Cross     : confirm / attack
    'Buttons/1':     (['K'],                          ['Button W']),                 # Square    : secondary
    'Buttons/A':     (['L'],                          ['Button E', 'Shoulder R']),   # Circle / R1
    'Buttons/B':     (['I'],                          ['Button N', 'Shoulder L']),   # Triangle / L1
    'Buttons/+':     (['RETURN'],                     ['Start']),
    'Buttons/-':     (['BACK'],                       ['Back']),
    'Buttons/Home':  (['TAB'],                        ['Guide']),
    'D-Pad/Up':      (['W', 'UP'],                    ['Pad N', 'Left Y+']),
    'D-Pad/Down':    (['S', 'DOWN'],                  ['Pad S', 'Left Y-']),
    'D-Pad/Left':    (['A', 'LEFT'],                  ['Pad W', 'Left X-']),
    'D-Pad/Right':   (['D', 'RIGHT'],                 ['Pad E', 'Left X+']),
}


def discover_gamepads(log_path):
    pads = []
    if not os.path.exists(log_path):
        return pads
    for line in open(log_path, encoding='utf-8', errors='replace'):
        m = re.search(r'Added device: (SDL/\d+/.+?)\s*$', line)
        if m and m.group(1) not in pads:
            pads.append(m.group(1))
    return pads


def build_profile(slot, use_keyboard, pad):
    """Return the ini text for [Wiimote<slot>]."""
    lines = [f'[Wiimote{slot}]', f'Device = {pad if pad else KEYBOARD}']
    for control, (keys, buttons) in MAP.items():
        terms = []
        if use_keyboard:
            terms += [f'`{KEYBOARD}:{k}`' for k in keys]
        if pad:
            terms += [f'`{pad}:{b}`' for b in buttons]
        if terms:
            lines.append(f'{control} = ' + ' | '.join(terms))
    if pad:
        lines.append(f'Rumble/Motor = `{pad}:Motor L` | `{pad}:Motor R`')
    lines += ['Extension = None', 'Options/Sideways Wiimote = True']
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--user-dir', default=r'C:\RumbleRecomp\build\userdir')
    ap.add_argument('--gamepad', action='append', help='explicit SDL device name, e.g. "SDL/0/PS4 Controller" (repeatable)')
    ap.add_argument('--no-keyboard', action='store_true')
    ap.add_argument('--no-gamepad', action='store_true', help='keyboard only (shipped default)')
    ap.add_argument('--out-dir', help='write here instead of <user-dir>/Config')
    a = ap.parse_args()

    cfg = a.out_dir or os.path.join(a.user_dir, 'Config')
    os.makedirs(cfg, exist_ok=True)
    pads = [] if a.no_gamepad else (a.gamepad or discover_gamepads(os.path.join(a.user_dir, 'Logs', 'dolphin.log')))
    pads = pads[:4]

    profiles = [build_profile(1, not a.no_keyboard, pads[0] if pads else None)]
    for i, pad in enumerate(pads[1:], start=2):
        profiles.append(build_profile(i, False, pad))
    with open(os.path.join(cfg, 'WiimoteNew.ini'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Generated by tools/make_controller_config.py\n' + '\n'.join(profiles) + '\n')

    sources = ['[Wiimote1]', 'Source = 1']  # 1 = emulated
    for i in range(2, len(profiles) + 1):
        sources += [f'[Wiimote{i}]', 'Source = 1']
    with open(os.path.join(cfg, 'Wiimote.ini'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Generated by tools/make_controller_config.py\n' + '\n'.join(sources) + '\n')

    print(f'wrote {cfg}\\WiimoteNew.ini and Wiimote.ini: player 1 = keyboard' +
          (f' + {pads[0]}' if pads else '') + ''.join(f'; player {i} = {p}' for i, p in enumerate(pads[1:], start=2)))


if __name__ == '__main__':
    main()
